# Generated by Django 2.2.4 on 2019-09-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_attendance', '0003_auto_20190919_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
    ]
