# Generated by Django 2.2.4 on 2019-09-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_attendance', '0006_auto_20190919_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='users/%y/%m/%d/'),
        ),
    ]
