# Generated by Django 2.2.4 on 2019-09-20 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_attendance', '0007_auto_20190920_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='users/%y/%m/%d'),
        ),
    ]
