# Generated by Django 2.2.4 on 2019-09-23 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_attendance', '0010_auto_20190924_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_attendance',
            name='course',
        ),
    ]
