# Generated by Django 2.2.4 on 2019-09-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_attendance', '0011_remove_student_attendance_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='course',
            field=models.CharField(max_length=250),
        ),
    ]
