# Generated by Django 2.2.4 on 2019-09-23 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_attendance', '0013_auto_20190924_0029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='s_attendance',
            old_name='user',
            new_name='student',
        ),
    ]
