# Generated by Django 2.2.4 on 2019-09-24 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_attendance', '0015_auto_20190924_1243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='s_attendance',
            old_name='student',
            new_name='user',
        ),
    ]
