# Generated by Django 2.2.4 on 2019-09-25 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_attendance', '0016_auto_20190924_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s_attendance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
