# Generated by Django 2.2.4 on 2019-09-09 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=250)),
                ('course_fee', models.CharField(max_length=250)),
                ('course_duration', models.CharField(max_length=250)),
                ('course_detail', models.CharField(max_length=2000)),
            ],
            options={
                'ordering': ('course_name',),
            },
        ),
    ]
