# Generated by Django 2.2.4 on 2019-09-09 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_duration',
            field=models.FloatField(max_length=250),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_fee',
            field=models.FloatField(max_length=250),
        ),
    ]
