# Generated by Django 2.2.4 on 2019-09-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20190909_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_duration',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_fee',
            field=models.CharField(max_length=250),
        ),
    ]
