# Generated by Django 2.2.4 on 2019-09-11 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_contactus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contactus',
        ),
    ]
